"""Generate valid .xsq XML files for xLights."""

from __future__ import annotations

import logging
import xml.etree.ElementTree as ET
from collections.abc import Iterable
from pathlib import Path

from pydantic import BaseModel, Field

from xlights_mcp.xlights.models import ShowConfig
from xlights_mcp.xlights.palettes import DEFAULT_PALETTE, ColorPalette

logger = logging.getLogger(__name__)

FRAME_MS = 25
GENERATOR_COMMENT = "Generated by xLights MCP Server"
HEAD_BYTES = 4096
DEFAULT_XLIGHTS_VERSION = "2025.13"


class EffectPlacement(BaseModel):
    """A single effect placed on a model at a specific time."""

    model_name: str
    layer: int = 0
    effect_name: str
    start_time_ms: int
    end_time_ms: int
    settings: dict[str, str] = Field(default_factory=dict)
    palette: ColorPalette | None = None


class TimingTrackLabel(BaseModel):
    """A label in a timing track (phoneme, word, etc.)."""

    label: str
    start_time_ms: int
    end_time_ms: int


class TimingTrack(BaseModel):
    """A timing track (e.g., lyric/phoneme track) for the sequence."""

    name: str
    labels: list[list[TimingTrackLabel]] = Field(default_factory=list)  # one list per layer


class SequenceSpec(BaseModel):
    """Complete specification for generating a sequence."""

    song_title: str = ""
    artist: str = ""
    album: str = ""
    media_file: str = ""
    duration_ms: int = 0
    xlights_version: str = DEFAULT_XLIGHTS_VERSION
    timing_ms: int = FRAME_MS  # frame rate in ms (25ms = 40fps)
    effects: list[EffectPlacement] = Field(default_factory=list)
    timing_tracks: list[TimingTrack] = Field(default_factory=list)


def write_xsq(
    spec: SequenceSpec,
    show_config: ShowConfig,
    output_path: Path,
) -> Path:
    """Generate a .xsq file from a sequence specification.

    Args:
        spec: The sequence specification with effects and timing tracks
        show_config: The show configuration (models, controllers)
        output_path: Where to write the .xsq file

    Returns:
        Path to the written .xsq file
    """
    root = ET.Element("xsequence")
    root.set("BaseChannel", "0")
    root.set("ChanCtrlBasic", "0")
    root.set("ChanCtrlColor", "0")
    root.set("FixedPointTiming", "1")
    root.set("ModelBlending", "true")

    # <head> section
    head = ET.SubElement(root, "head")
    _add_text_elem(head, "version", spec.xlights_version)
    _add_text_elem(head, "author", "")
    _add_text_elem(head, "author-email", "")
    _add_text_elem(head, "author-website", "")
    _add_text_elem(head, "song", spec.song_title)
    _add_text_elem(head, "artist", spec.artist)
    _add_text_elem(head, "album", spec.album)
    _add_text_elem(head, "MusicURL", "")
    _add_text_elem(head, "comment", GENERATOR_COMMENT)
    _add_text_elem(head, "sequenceTiming", f"{spec.timing_ms} ms")
    _add_text_elem(head, "sequenceType", "Media")
    _add_text_elem(head, "mediaFile", spec.media_file)
    _add_text_elem(head, "sequenceDuration", f"{spec.duration_ms / 1000:.3f}")
    ET.SubElement(head, "imageDir")

    # <nextid>
    _add_text_elem(root, "nextid", "1")

    # <Jukebox>
    ET.SubElement(root, "Jukebox")

    default_palette = DEFAULT_PALETTE.to_xlights_string()
    palette_index: dict[str, int] = {}
    settings_index: dict[str, int] = {}
    effects_by_model: dict[str, list[tuple[EffectPlacement, int, int]]] = {}
    for eff in spec.effects:
        ref = settings_index.setdefault(_build_effect_settings(eff), len(settings_index))
        palette_str = eff.palette.to_xlights_string() if eff.palette else default_palette
        palette = palette_index.setdefault(palette_str, len(palette_index))
        effects_by_model.setdefault(eff.model_name, []).append((eff, ref, palette))

    # <ColorPalettes>
    palettes_elem = ET.SubElement(root, "ColorPalettes")
    for ps in palette_index:
        ET.SubElement(palettes_elem, "ColorPalette").text = ps

    # <EffectDB> — deduplicated effect settings
    effect_db_elem = ET.SubElement(root, "EffectDB")
    for settings_str in settings_index:
        ET.SubElement(effect_db_elem, "Effect").text = settings_str

    # <DataLayers>
    data_layers = ET.SubElement(root, "DataLayers")
    dl = ET.SubElement(data_layers, "DataLayer")
    dl.set("name", "Nutcracker")
    dl.set("source", "1")

    display_elems = ET.SubElement(root, "DisplayElements")
    all_names = _element_order(effects_by_model.keys(), show_config)

    # Timing tracks (lyric tracks, etc.) come first, as in hand-made sequences
    for track in spec.timing_tracks:
        de = ET.SubElement(display_elems, "Element")
        de.set("collapsed", "0")
        de.set("type", "timing")
        de.set("name", track.name)
        de.set("visible", "1")
        de.set("views", "")
        de.set("active", "0")

    for name in all_names:
        de = ET.SubElement(display_elems, "Element")
        de.set("collapsed", "0")
        de.set("type", "model")
        de.set("name", name)
        de.set("visible", "1")
        de.set("active", "0")

    # <ElementEffects> — actual effect placements per model
    element_effects = ET.SubElement(root, "ElementEffects")

    for track in spec.timing_tracks:
        te = ET.SubElement(element_effects, "Element")
        te.set("type", "timing")
        te.set("name", track.name)

        for layer_labels in track.labels:
            layer_elem = ET.SubElement(te, "EffectLayer")
            for lbl in sorted(layer_labels, key=lambda l: l.start_time_ms):
                label_elem = ET.SubElement(layer_elem, "Effect")
                label_elem.set("label", lbl.label)
                label_elem.set("startTime", str(lbl.start_time_ms))
                label_elem.set("endTime", str(lbl.end_time_ms))

    for name in all_names:
        ee = ET.SubElement(element_effects, "Element")
        ee.set("type", "model")
        ee.set("name", name)

        layers: dict[int, list[tuple[EffectPlacement, int, int]]] = {}
        for entry in effects_by_model.get(name, []):
            layers.setdefault(entry[0].layer, []).append(entry)

        for layer_idx in range(max(layers, default=0) + 1):
            layer_elem = ET.SubElement(ee, "EffectLayer")
            for eff, ref, palette in sorted(layers.get(layer_idx, []), key=lambda e: e[0].start_time_ms):
                effect_elem = ET.SubElement(layer_elem, "Effect")
                effect_elem.set("name", eff.effect_name)
                effect_elem.set("startTime", str(eff.start_time_ms))
                effect_elem.set("endTime", str(eff.end_time_ms))
                effect_elem.set("ref", str(ref))
                effect_elem.set("palette", str(palette))

    # <lastView>
    _add_text_elem(root, "lastView", "0")

    # <TimingTags>
    ET.SubElement(root, "TimingTags")

    # Write to file — use double quotes in XML declaration to match xLights format
    tree = ET.ElementTree(root)
    ET.indent(tree, space="  ")

    with open(output_path, "w", encoding="UTF-8") as f:
        f.write('<?xml version="1.0" encoding="UTF-8"?>\n')
        tree.write(f, encoding="unicode", xml_declaration=False)

    logger.info(f"Wrote sequence to {output_path}")
    return output_path


def _element_order(used: Iterable[str], show_config: ShowConfig) -> list[str]:
    used = set(used)
    show_order = [g.name for g in show_config.model_groups] + [m.name for m in show_config.models]
    ordered = list(dict.fromkeys(name for name in show_order if name in used))
    return ordered + sorted(used.difference(ordered))


def is_generated_sequence(head: bytes) -> bool:
    return f"<comment>{GENERATOR_COMMENT}</comment>".encode() in head


def _build_effect_settings(eff: EffectPlacement) -> str:
    """Build the effect settings string for the EffectDB."""
    return ",".join(f"{key}={val}" for key, val in eff.settings.items())


def _add_text_elem(parent: ET.Element, tag: str, text: str) -> ET.Element:
    """Add a child element with text content."""
    elem = ET.SubElement(parent, tag)
    elem.text = text
    return elem
